export type SpeciesContent = {
  _id: string;
  aphiaId: string;
  articleUrl: string;
  articleTitle: string;
  commonNames: string[];
  scientificName: string;
  introduction: string;
  imageUrls: string[];
  iconUrl: string;
  species: string;
  genus: string;
  family: string;
  order: string;
  class: string;
  phylum: string;
  kingdom: string;
  domain: string;
  visibility: boolean;
  locations: string[];
};
