name: Node.js CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies (backend)
              working-directory: ./backend
              run: npm install

            - name: Install dependencies (frontend)
              working-directory: ./frontend
              run: npm install

            - name: Run Prettier Check (backend)
              working-directory: ./backend
              run: npm run format -- --check

            - name: Run Prettier Check (frontend)
              working-directory: ./frontend
              run: npm run format -- --check

            - name: Run tests
              working-directory: ./backend
              run: npm test
